-- Inventory stock levels. Schema owned by Flyway (standards rule 1).
CREATE TABLE stock (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku       VARCHAR(64) NOT NULL UNIQUE,
    available INTEGER     NOT NULL,
    version   BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT stock_non_negative CHECK (available >= 0)  -- oversell is impossible at the DB level too
);
