-- Inventory's transactional outbox (outgoing StockReserved/StockRejected) + consumer dedupe.
CREATE TABLE outbox_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic        VARCHAR(128) NOT NULL,
    message_key  VARCHAR(128) NOT NULL,
    payload      TEXT         NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    published_at TIMESTAMP,
    attempts     INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX idx_outbox_unpublished ON outbox_event (created_at) WHERE published_at IS NULL;

-- Keyed by orderId: an order is reserved at most once, however many times OrderPlaced is delivered.
CREATE TABLE processed_message (
    message_key  VARCHAR(160) PRIMARY KEY,
    processed_at TIMESTAMP    NOT NULL
);
