-- Orders + transactional outbox + consumer dedupe. Schema owned by Flyway (standards rule 1).

CREATE TABLE orders (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   VARCHAR(64)   NOT NULL UNIQUE,
    sku        VARCHAR(64)   NOT NULL,
    quantity   INTEGER       NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    state      VARCHAR(16)   NOT NULL,
    created_at TIMESTAMP     NOT NULL
);

CREATE TABLE outbox_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic        VARCHAR(128) NOT NULL,
    message_key  VARCHAR(128) NOT NULL,
    payload      TEXT         NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    published_at TIMESTAMP,
    attempts     INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX idx_outbox_unpublished ON outbox_event (created_at) WHERE published_at IS NULL;

-- Idempotency: keyed by orderId:eventType, inserted in the same tx as the handler's side effect.
CREATE TABLE processed_message (
    message_key  VARCHAR(160) PRIMARY KEY,
    processed_at TIMESTAMP    NOT NULL
);
