-- Shipments + outbox. Schema owned by Flyway (standards rule 1). The unique order_id doubles as
-- the idempotency guard: at most one shipment per order.
CREATE TABLE shipment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    VARCHAR(64) NOT NULL UNIQUE,
    tracking_id VARCHAR(64) NOT NULL,
    created_at  TIMESTAMP   NOT NULL
);

CREATE TABLE outbox_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic        VARCHAR(128) NOT NULL,
    message_key  VARCHAR(128) NOT NULL,
    payload      TEXT         NOT NULL,
    created_at   TIMESTAMP    NOT NULL,
    published_at TIMESTAMP,
    attempts     INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX idx_outbox_unpublished ON outbox_event (created_at) WHERE published_at IS NULL;
